// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavbarMangaSearchController from "./navbar_manga_search_controller"
application.register("navbar-manga-search", NavbarMangaSearchController)

import RandomController from "./random_controller"
application.register("random", RandomController)
